---
- name: Apply Common setup
  import_playbook: playbooks/common.yml

- name: Apply System Hardening
  import_playbook: playbooks/hardening.yml

- name: Install Docker
  import_playbook: playbooks/docker.yml
