---
# List of non-root users to add to the docker group
docker_users:
  - "vagrant"

# Daemon configuration settings
docker_log_max_size: "100m"
docker_log_max_file: "3"
docker_cgroup_driver: "systemd"
